package com.rmbih.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RmbihPicTExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table rmbih_pic_t
	 * @mbg.generated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table rmbih_pic_t
	 * @mbg.generated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table rmbih_pic_t
	 * @mbg.generated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rmbih_pic_t
	 * @mbg.generated
	 */
	public RmbihPicTExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rmbih_pic_t
	 * @mbg.generated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rmbih_pic_t
	 * @mbg.generated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rmbih_pic_t
	 * @mbg.generated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rmbih_pic_t
	 * @mbg.generated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rmbih_pic_t
	 * @mbg.generated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rmbih_pic_t
	 * @mbg.generated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rmbih_pic_t
	 * @mbg.generated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rmbih_pic_t
	 * @mbg.generated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rmbih_pic_t
	 * @mbg.generated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rmbih_pic_t
	 * @mbg.generated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table rmbih_pic_t
	 * @mbg.generated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andPicUrlIsNull() {
			addCriterion("PIC_URL is null");
			return (Criteria) this;
		}

		public Criteria andPicUrlIsNotNull() {
			addCriterion("PIC_URL is not null");
			return (Criteria) this;
		}

		public Criteria andPicUrlEqualTo(String value) {
			addCriterion("PIC_URL =", value, "picUrl");
			return (Criteria) this;
		}

		public Criteria andPicUrlNotEqualTo(String value) {
			addCriterion("PIC_URL <>", value, "picUrl");
			return (Criteria) this;
		}

		public Criteria andPicUrlGreaterThan(String value) {
			addCriterion("PIC_URL >", value, "picUrl");
			return (Criteria) this;
		}

		public Criteria andPicUrlGreaterThanOrEqualTo(String value) {
			addCriterion("PIC_URL >=", value, "picUrl");
			return (Criteria) this;
		}

		public Criteria andPicUrlLessThan(String value) {
			addCriterion("PIC_URL <", value, "picUrl");
			return (Criteria) this;
		}

		public Criteria andPicUrlLessThanOrEqualTo(String value) {
			addCriterion("PIC_URL <=", value, "picUrl");
			return (Criteria) this;
		}

		public Criteria andPicUrlLike(String value) {
			addCriterion("PIC_URL like", value, "picUrl");
			return (Criteria) this;
		}

		public Criteria andPicUrlNotLike(String value) {
			addCriterion("PIC_URL not like", value, "picUrl");
			return (Criteria) this;
		}

		public Criteria andPicUrlIn(List<String> values) {
			addCriterion("PIC_URL in", values, "picUrl");
			return (Criteria) this;
		}

		public Criteria andPicUrlNotIn(List<String> values) {
			addCriterion("PIC_URL not in", values, "picUrl");
			return (Criteria) this;
		}

		public Criteria andPicUrlBetween(String value1, String value2) {
			addCriterion("PIC_URL between", value1, value2, "picUrl");
			return (Criteria) this;
		}

		public Criteria andPicUrlNotBetween(String value1, String value2) {
			addCriterion("PIC_URL not between", value1, value2, "picUrl");
			return (Criteria) this;
		}

		public Criteria andPicContentIsNull() {
			addCriterion("PIC_CONTENT is null");
			return (Criteria) this;
		}

		public Criteria andPicContentIsNotNull() {
			addCriterion("PIC_CONTENT is not null");
			return (Criteria) this;
		}

		public Criteria andPicContentEqualTo(String value) {
			addCriterion("PIC_CONTENT =", value, "picContent");
			return (Criteria) this;
		}

		public Criteria andPicContentNotEqualTo(String value) {
			addCriterion("PIC_CONTENT <>", value, "picContent");
			return (Criteria) this;
		}

		public Criteria andPicContentGreaterThan(String value) {
			addCriterion("PIC_CONTENT >", value, "picContent");
			return (Criteria) this;
		}

		public Criteria andPicContentGreaterThanOrEqualTo(String value) {
			addCriterion("PIC_CONTENT >=", value, "picContent");
			return (Criteria) this;
		}

		public Criteria andPicContentLessThan(String value) {
			addCriterion("PIC_CONTENT <", value, "picContent");
			return (Criteria) this;
		}

		public Criteria andPicContentLessThanOrEqualTo(String value) {
			addCriterion("PIC_CONTENT <=", value, "picContent");
			return (Criteria) this;
		}

		public Criteria andPicContentLike(String value) {
			addCriterion("PIC_CONTENT like", value, "picContent");
			return (Criteria) this;
		}

		public Criteria andPicContentNotLike(String value) {
			addCriterion("PIC_CONTENT not like", value, "picContent");
			return (Criteria) this;
		}

		public Criteria andPicContentIn(List<String> values) {
			addCriterion("PIC_CONTENT in", values, "picContent");
			return (Criteria) this;
		}

		public Criteria andPicContentNotIn(List<String> values) {
			addCriterion("PIC_CONTENT not in", values, "picContent");
			return (Criteria) this;
		}

		public Criteria andPicContentBetween(String value1, String value2) {
			addCriterion("PIC_CONTENT between", value1, value2, "picContent");
			return (Criteria) this;
		}

		public Criteria andPicContentNotBetween(String value1, String value2) {
			addCriterion("PIC_CONTENT not between", value1, value2, "picContent");
			return (Criteria) this;
		}

		public Criteria andPicAltIsNull() {
			addCriterion("PIC_ALT is null");
			return (Criteria) this;
		}

		public Criteria andPicAltIsNotNull() {
			addCriterion("PIC_ALT is not null");
			return (Criteria) this;
		}

		public Criteria andPicAltEqualTo(String value) {
			addCriterion("PIC_ALT =", value, "picAlt");
			return (Criteria) this;
		}

		public Criteria andPicAltNotEqualTo(String value) {
			addCriterion("PIC_ALT <>", value, "picAlt");
			return (Criteria) this;
		}

		public Criteria andPicAltGreaterThan(String value) {
			addCriterion("PIC_ALT >", value, "picAlt");
			return (Criteria) this;
		}

		public Criteria andPicAltGreaterThanOrEqualTo(String value) {
			addCriterion("PIC_ALT >=", value, "picAlt");
			return (Criteria) this;
		}

		public Criteria andPicAltLessThan(String value) {
			addCriterion("PIC_ALT <", value, "picAlt");
			return (Criteria) this;
		}

		public Criteria andPicAltLessThanOrEqualTo(String value) {
			addCriterion("PIC_ALT <=", value, "picAlt");
			return (Criteria) this;
		}

		public Criteria andPicAltLike(String value) {
			addCriterion("PIC_ALT like", value, "picAlt");
			return (Criteria) this;
		}

		public Criteria andPicAltNotLike(String value) {
			addCriterion("PIC_ALT not like", value, "picAlt");
			return (Criteria) this;
		}

		public Criteria andPicAltIn(List<String> values) {
			addCriterion("PIC_ALT in", values, "picAlt");
			return (Criteria) this;
		}

		public Criteria andPicAltNotIn(List<String> values) {
			addCriterion("PIC_ALT not in", values, "picAlt");
			return (Criteria) this;
		}

		public Criteria andPicAltBetween(String value1, String value2) {
			addCriterion("PIC_ALT between", value1, value2, "picAlt");
			return (Criteria) this;
		}

		public Criteria andPicAltNotBetween(String value1, String value2) {
			addCriterion("PIC_ALT not between", value1, value2, "picAlt");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("USER_ID is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("USER_ID is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(Integer value) {
			addCriterion("USER_ID =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(Integer value) {
			addCriterion("USER_ID <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(Integer value) {
			addCriterion("USER_ID >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("USER_ID >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(Integer value) {
			addCriterion("USER_ID <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(Integer value) {
			addCriterion("USER_ID <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<Integer> values) {
			addCriterion("USER_ID in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<Integer> values) {
			addCriterion("USER_ID not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(Integer value1, Integer value2) {
			addCriterion("USER_ID between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
			addCriterion("USER_ID not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andInputNameIsNull() {
			addCriterion("INPUT_NAME is null");
			return (Criteria) this;
		}

		public Criteria andInputNameIsNotNull() {
			addCriterion("INPUT_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andInputNameEqualTo(String value) {
			addCriterion("INPUT_NAME =", value, "inputName");
			return (Criteria) this;
		}

		public Criteria andInputNameNotEqualTo(String value) {
			addCriterion("INPUT_NAME <>", value, "inputName");
			return (Criteria) this;
		}

		public Criteria andInputNameGreaterThan(String value) {
			addCriterion("INPUT_NAME >", value, "inputName");
			return (Criteria) this;
		}

		public Criteria andInputNameGreaterThanOrEqualTo(String value) {
			addCriterion("INPUT_NAME >=", value, "inputName");
			return (Criteria) this;
		}

		public Criteria andInputNameLessThan(String value) {
			addCriterion("INPUT_NAME <", value, "inputName");
			return (Criteria) this;
		}

		public Criteria andInputNameLessThanOrEqualTo(String value) {
			addCriterion("INPUT_NAME <=", value, "inputName");
			return (Criteria) this;
		}

		public Criteria andInputNameLike(String value) {
			addCriterion("INPUT_NAME like", value, "inputName");
			return (Criteria) this;
		}

		public Criteria andInputNameNotLike(String value) {
			addCriterion("INPUT_NAME not like", value, "inputName");
			return (Criteria) this;
		}

		public Criteria andInputNameIn(List<String> values) {
			addCriterion("INPUT_NAME in", values, "inputName");
			return (Criteria) this;
		}

		public Criteria andInputNameNotIn(List<String> values) {
			addCriterion("INPUT_NAME not in", values, "inputName");
			return (Criteria) this;
		}

		public Criteria andInputNameBetween(String value1, String value2) {
			addCriterion("INPUT_NAME between", value1, value2, "inputName");
			return (Criteria) this;
		}

		public Criteria andInputNameNotBetween(String value1, String value2) {
			addCriterion("INPUT_NAME not between", value1, value2, "inputName");
			return (Criteria) this;
		}

		public Criteria andInputDateIsNull() {
			addCriterion("INPUT_DATE is null");
			return (Criteria) this;
		}

		public Criteria andInputDateIsNotNull() {
			addCriterion("INPUT_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andInputDateEqualTo(Date value) {
			addCriterion("INPUT_DATE =", value, "inputDate");
			return (Criteria) this;
		}

		public Criteria andInputDateNotEqualTo(Date value) {
			addCriterion("INPUT_DATE <>", value, "inputDate");
			return (Criteria) this;
		}

		public Criteria andInputDateGreaterThan(Date value) {
			addCriterion("INPUT_DATE >", value, "inputDate");
			return (Criteria) this;
		}

		public Criteria andInputDateGreaterThanOrEqualTo(Date value) {
			addCriterion("INPUT_DATE >=", value, "inputDate");
			return (Criteria) this;
		}

		public Criteria andInputDateLessThan(Date value) {
			addCriterion("INPUT_DATE <", value, "inputDate");
			return (Criteria) this;
		}

		public Criteria andInputDateLessThanOrEqualTo(Date value) {
			addCriterion("INPUT_DATE <=", value, "inputDate");
			return (Criteria) this;
		}

		public Criteria andInputDateIn(List<Date> values) {
			addCriterion("INPUT_DATE in", values, "inputDate");
			return (Criteria) this;
		}

		public Criteria andInputDateNotIn(List<Date> values) {
			addCriterion("INPUT_DATE not in", values, "inputDate");
			return (Criteria) this;
		}

		public Criteria andInputDateBetween(Date value1, Date value2) {
			addCriterion("INPUT_DATE between", value1, value2, "inputDate");
			return (Criteria) this;
		}

		public Criteria andInputDateNotBetween(Date value1, Date value2) {
			addCriterion("INPUT_DATE not between", value1, value2, "inputDate");
			return (Criteria) this;
		}

		public Criteria andUpdateNameIsNull() {
			addCriterion("UPDATE_NAME is null");
			return (Criteria) this;
		}

		public Criteria andUpdateNameIsNotNull() {
			addCriterion("UPDATE_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateNameEqualTo(String value) {
			addCriterion("UPDATE_NAME =", value, "updateName");
			return (Criteria) this;
		}

		public Criteria andUpdateNameNotEqualTo(String value) {
			addCriterion("UPDATE_NAME <>", value, "updateName");
			return (Criteria) this;
		}

		public Criteria andUpdateNameGreaterThan(String value) {
			addCriterion("UPDATE_NAME >", value, "updateName");
			return (Criteria) this;
		}

		public Criteria andUpdateNameGreaterThanOrEqualTo(String value) {
			addCriterion("UPDATE_NAME >=", value, "updateName");
			return (Criteria) this;
		}

		public Criteria andUpdateNameLessThan(String value) {
			addCriterion("UPDATE_NAME <", value, "updateName");
			return (Criteria) this;
		}

		public Criteria andUpdateNameLessThanOrEqualTo(String value) {
			addCriterion("UPDATE_NAME <=", value, "updateName");
			return (Criteria) this;
		}

		public Criteria andUpdateNameLike(String value) {
			addCriterion("UPDATE_NAME like", value, "updateName");
			return (Criteria) this;
		}

		public Criteria andUpdateNameNotLike(String value) {
			addCriterion("UPDATE_NAME not like", value, "updateName");
			return (Criteria) this;
		}

		public Criteria andUpdateNameIn(List<String> values) {
			addCriterion("UPDATE_NAME in", values, "updateName");
			return (Criteria) this;
		}

		public Criteria andUpdateNameNotIn(List<String> values) {
			addCriterion("UPDATE_NAME not in", values, "updateName");
			return (Criteria) this;
		}

		public Criteria andUpdateNameBetween(String value1, String value2) {
			addCriterion("UPDATE_NAME between", value1, value2, "updateName");
			return (Criteria) this;
		}

		public Criteria andUpdateNameNotBetween(String value1, String value2) {
			addCriterion("UPDATE_NAME not between", value1, value2, "updateName");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIsNull() {
			addCriterion("UPDATE_DATE is null");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIsNotNull() {
			addCriterion("UPDATE_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateDateEqualTo(Date value) {
			addCriterion("UPDATE_DATE =", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotEqualTo(Date value) {
			addCriterion("UPDATE_DATE <>", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateGreaterThan(Date value) {
			addCriterion("UPDATE_DATE >", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("UPDATE_DATE >=", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateLessThan(Date value) {
			addCriterion("UPDATE_DATE <", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
			addCriterion("UPDATE_DATE <=", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIn(List<Date> values) {
			addCriterion("UPDATE_DATE in", values, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotIn(List<Date> values) {
			addCriterion("UPDATE_DATE not in", values, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateBetween(Date value1, Date value2) {
			addCriterion("UPDATE_DATE between", value1, value2, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
			addCriterion("UPDATE_DATE not between", value1, value2, "updateDate");
			return (Criteria) this;
		}

		public Criteria andDelsignIsNull() {
			addCriterion("DELSIGN is null");
			return (Criteria) this;
		}

		public Criteria andDelsignIsNotNull() {
			addCriterion("DELSIGN is not null");
			return (Criteria) this;
		}

		public Criteria andDelsignEqualTo(Integer value) {
			addCriterion("DELSIGN =", value, "delsign");
			return (Criteria) this;
		}

		public Criteria andDelsignNotEqualTo(Integer value) {
			addCriterion("DELSIGN <>", value, "delsign");
			return (Criteria) this;
		}

		public Criteria andDelsignGreaterThan(Integer value) {
			addCriterion("DELSIGN >", value, "delsign");
			return (Criteria) this;
		}

		public Criteria andDelsignGreaterThanOrEqualTo(Integer value) {
			addCriterion("DELSIGN >=", value, "delsign");
			return (Criteria) this;
		}

		public Criteria andDelsignLessThan(Integer value) {
			addCriterion("DELSIGN <", value, "delsign");
			return (Criteria) this;
		}

		public Criteria andDelsignLessThanOrEqualTo(Integer value) {
			addCriterion("DELSIGN <=", value, "delsign");
			return (Criteria) this;
		}

		public Criteria andDelsignIn(List<Integer> values) {
			addCriterion("DELSIGN in", values, "delsign");
			return (Criteria) this;
		}

		public Criteria andDelsignNotIn(List<Integer> values) {
			addCriterion("DELSIGN not in", values, "delsign");
			return (Criteria) this;
		}

		public Criteria andDelsignBetween(Integer value1, Integer value2) {
			addCriterion("DELSIGN between", value1, value2, "delsign");
			return (Criteria) this;
		}

		public Criteria andDelsignNotBetween(Integer value1, Integer value2) {
			addCriterion("DELSIGN not between", value1, value2, "delsign");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table rmbih_pic_t
	 * @mbg.generated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rmbih_pic_t
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}