package com.rmbih.model;

import java.util.ArrayList;
import java.util.List;

public class RmbihUserTExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table rmbih_user_t
	 * @mbg.generated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table rmbih_user_t
	 * @mbg.generated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table rmbih_user_t
	 * @mbg.generated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rmbih_user_t
	 * @mbg.generated
	 */
	public RmbihUserTExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rmbih_user_t
	 * @mbg.generated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rmbih_user_t
	 * @mbg.generated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rmbih_user_t
	 * @mbg.generated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rmbih_user_t
	 * @mbg.generated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rmbih_user_t
	 * @mbg.generated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rmbih_user_t
	 * @mbg.generated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rmbih_user_t
	 * @mbg.generated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rmbih_user_t
	 * @mbg.generated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rmbih_user_t
	 * @mbg.generated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rmbih_user_t
	 * @mbg.generated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table rmbih_user_t
	 * @mbg.generated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andLoginNameIsNull() {
			addCriterion("LOGIN_NAME is null");
			return (Criteria) this;
		}

		public Criteria andLoginNameIsNotNull() {
			addCriterion("LOGIN_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andLoginNameEqualTo(String value) {
			addCriterion("LOGIN_NAME =", value, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameNotEqualTo(String value) {
			addCriterion("LOGIN_NAME <>", value, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameGreaterThan(String value) {
			addCriterion("LOGIN_NAME >", value, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameGreaterThanOrEqualTo(String value) {
			addCriterion("LOGIN_NAME >=", value, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameLessThan(String value) {
			addCriterion("LOGIN_NAME <", value, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameLessThanOrEqualTo(String value) {
			addCriterion("LOGIN_NAME <=", value, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameLike(String value) {
			addCriterion("LOGIN_NAME like", value, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameNotLike(String value) {
			addCriterion("LOGIN_NAME not like", value, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameIn(List<String> values) {
			addCriterion("LOGIN_NAME in", values, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameNotIn(List<String> values) {
			addCriterion("LOGIN_NAME not in", values, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameBetween(String value1, String value2) {
			addCriterion("LOGIN_NAME between", value1, value2, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameNotBetween(String value1, String value2) {
			addCriterion("LOGIN_NAME not between", value1, value2, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginPasswordIsNull() {
			addCriterion("LOGIN_PASSWORD is null");
			return (Criteria) this;
		}

		public Criteria andLoginPasswordIsNotNull() {
			addCriterion("LOGIN_PASSWORD is not null");
			return (Criteria) this;
		}

		public Criteria andLoginPasswordEqualTo(String value) {
			addCriterion("LOGIN_PASSWORD =", value, "loginPassword");
			return (Criteria) this;
		}

		public Criteria andLoginPasswordNotEqualTo(String value) {
			addCriterion("LOGIN_PASSWORD <>", value, "loginPassword");
			return (Criteria) this;
		}

		public Criteria andLoginPasswordGreaterThan(String value) {
			addCriterion("LOGIN_PASSWORD >", value, "loginPassword");
			return (Criteria) this;
		}

		public Criteria andLoginPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("LOGIN_PASSWORD >=", value, "loginPassword");
			return (Criteria) this;
		}

		public Criteria andLoginPasswordLessThan(String value) {
			addCriterion("LOGIN_PASSWORD <", value, "loginPassword");
			return (Criteria) this;
		}

		public Criteria andLoginPasswordLessThanOrEqualTo(String value) {
			addCriterion("LOGIN_PASSWORD <=", value, "loginPassword");
			return (Criteria) this;
		}

		public Criteria andLoginPasswordLike(String value) {
			addCriterion("LOGIN_PASSWORD like", value, "loginPassword");
			return (Criteria) this;
		}

		public Criteria andLoginPasswordNotLike(String value) {
			addCriterion("LOGIN_PASSWORD not like", value, "loginPassword");
			return (Criteria) this;
		}

		public Criteria andLoginPasswordIn(List<String> values) {
			addCriterion("LOGIN_PASSWORD in", values, "loginPassword");
			return (Criteria) this;
		}

		public Criteria andLoginPasswordNotIn(List<String> values) {
			addCriterion("LOGIN_PASSWORD not in", values, "loginPassword");
			return (Criteria) this;
		}

		public Criteria andLoginPasswordBetween(String value1, String value2) {
			addCriterion("LOGIN_PASSWORD between", value1, value2, "loginPassword");
			return (Criteria) this;
		}

		public Criteria andLoginPasswordNotBetween(String value1, String value2) {
			addCriterion("LOGIN_PASSWORD not between", value1, value2, "loginPassword");
			return (Criteria) this;
		}

		public Criteria andUserNameIsNull() {
			addCriterion("USER_NAME is null");
			return (Criteria) this;
		}

		public Criteria andUserNameIsNotNull() {
			addCriterion("USER_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andUserNameEqualTo(String value) {
			addCriterion("USER_NAME =", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotEqualTo(String value) {
			addCriterion("USER_NAME <>", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameGreaterThan(String value) {
			addCriterion("USER_NAME >", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameGreaterThanOrEqualTo(String value) {
			addCriterion("USER_NAME >=", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLessThan(String value) {
			addCriterion("USER_NAME <", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLessThanOrEqualTo(String value) {
			addCriterion("USER_NAME <=", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLike(String value) {
			addCriterion("USER_NAME like", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotLike(String value) {
			addCriterion("USER_NAME not like", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameIn(List<String> values) {
			addCriterion("USER_NAME in", values, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotIn(List<String> values) {
			addCriterion("USER_NAME not in", values, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameBetween(String value1, String value2) {
			addCriterion("USER_NAME between", value1, value2, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotBetween(String value1, String value2) {
			addCriterion("USER_NAME not between", value1, value2, "userName");
			return (Criteria) this;
		}

		public Criteria andTokenIsNull() {
			addCriterion("TOKEN is null");
			return (Criteria) this;
		}

		public Criteria andTokenIsNotNull() {
			addCriterion("TOKEN is not null");
			return (Criteria) this;
		}

		public Criteria andTokenEqualTo(String value) {
			addCriterion("TOKEN =", value, "token");
			return (Criteria) this;
		}

		public Criteria andTokenNotEqualTo(String value) {
			addCriterion("TOKEN <>", value, "token");
			return (Criteria) this;
		}

		public Criteria andTokenGreaterThan(String value) {
			addCriterion("TOKEN >", value, "token");
			return (Criteria) this;
		}

		public Criteria andTokenGreaterThanOrEqualTo(String value) {
			addCriterion("TOKEN >=", value, "token");
			return (Criteria) this;
		}

		public Criteria andTokenLessThan(String value) {
			addCriterion("TOKEN <", value, "token");
			return (Criteria) this;
		}

		public Criteria andTokenLessThanOrEqualTo(String value) {
			addCriterion("TOKEN <=", value, "token");
			return (Criteria) this;
		}

		public Criteria andTokenLike(String value) {
			addCriterion("TOKEN like", value, "token");
			return (Criteria) this;
		}

		public Criteria andTokenNotLike(String value) {
			addCriterion("TOKEN not like", value, "token");
			return (Criteria) this;
		}

		public Criteria andTokenIn(List<String> values) {
			addCriterion("TOKEN in", values, "token");
			return (Criteria) this;
		}

		public Criteria andTokenNotIn(List<String> values) {
			addCriterion("TOKEN not in", values, "token");
			return (Criteria) this;
		}

		public Criteria andTokenBetween(String value1, String value2) {
			addCriterion("TOKEN between", value1, value2, "token");
			return (Criteria) this;
		}

		public Criteria andTokenNotBetween(String value1, String value2) {
			addCriterion("TOKEN not between", value1, value2, "token");
			return (Criteria) this;
		}

		public Criteria andRoleIsNull() {
			addCriterion("ROLE is null");
			return (Criteria) this;
		}

		public Criteria andRoleIsNotNull() {
			addCriterion("ROLE is not null");
			return (Criteria) this;
		}

		public Criteria andRoleEqualTo(String value) {
			addCriterion("ROLE =", value, "role");
			return (Criteria) this;
		}

		public Criteria andRoleNotEqualTo(String value) {
			addCriterion("ROLE <>", value, "role");
			return (Criteria) this;
		}

		public Criteria andRoleGreaterThan(String value) {
			addCriterion("ROLE >", value, "role");
			return (Criteria) this;
		}

		public Criteria andRoleGreaterThanOrEqualTo(String value) {
			addCriterion("ROLE >=", value, "role");
			return (Criteria) this;
		}

		public Criteria andRoleLessThan(String value) {
			addCriterion("ROLE <", value, "role");
			return (Criteria) this;
		}

		public Criteria andRoleLessThanOrEqualTo(String value) {
			addCriterion("ROLE <=", value, "role");
			return (Criteria) this;
		}

		public Criteria andRoleLike(String value) {
			addCriterion("ROLE like", value, "role");
			return (Criteria) this;
		}

		public Criteria andRoleNotLike(String value) {
			addCriterion("ROLE not like", value, "role");
			return (Criteria) this;
		}

		public Criteria andRoleIn(List<String> values) {
			addCriterion("ROLE in", values, "role");
			return (Criteria) this;
		}

		public Criteria andRoleNotIn(List<String> values) {
			addCriterion("ROLE not in", values, "role");
			return (Criteria) this;
		}

		public Criteria andRoleBetween(String value1, String value2) {
			addCriterion("ROLE between", value1, value2, "role");
			return (Criteria) this;
		}

		public Criteria andRoleNotBetween(String value1, String value2) {
			addCriterion("ROLE not between", value1, value2, "role");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("STATUS is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(String value) {
			addCriterion("STATUS =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("STATUS <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(String value) {
			addCriterion("STATUS >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value) {
			addCriterion("STATUS >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(String value) {
			addCriterion("STATUS <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value) {
			addCriterion("STATUS <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLike(String value) {
			addCriterion("STATUS like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotLike(String value) {
			addCriterion("STATUS not like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<String> values) {
			addCriterion("STATUS in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<String> values) {
			addCriterion("STATUS not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(String value1, String value2) {
			addCriterion("STATUS between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(String value1, String value2) {
			addCriterion("STATUS not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andMarkerFlagIsNull() {
			addCriterion("MARKER_FLAG is null");
			return (Criteria) this;
		}

		public Criteria andMarkerFlagIsNotNull() {
			addCriterion("MARKER_FLAG is not null");
			return (Criteria) this;
		}

		public Criteria andMarkerFlagEqualTo(String value) {
			addCriterion("MARKER_FLAG =", value, "markerFlag");
			return (Criteria) this;
		}

		public Criteria andMarkerFlagNotEqualTo(String value) {
			addCriterion("MARKER_FLAG <>", value, "markerFlag");
			return (Criteria) this;
		}

		public Criteria andMarkerFlagGreaterThan(String value) {
			addCriterion("MARKER_FLAG >", value, "markerFlag");
			return (Criteria) this;
		}

		public Criteria andMarkerFlagGreaterThanOrEqualTo(String value) {
			addCriterion("MARKER_FLAG >=", value, "markerFlag");
			return (Criteria) this;
		}

		public Criteria andMarkerFlagLessThan(String value) {
			addCriterion("MARKER_FLAG <", value, "markerFlag");
			return (Criteria) this;
		}

		public Criteria andMarkerFlagLessThanOrEqualTo(String value) {
			addCriterion("MARKER_FLAG <=", value, "markerFlag");
			return (Criteria) this;
		}

		public Criteria andMarkerFlagLike(String value) {
			addCriterion("MARKER_FLAG like", value, "markerFlag");
			return (Criteria) this;
		}

		public Criteria andMarkerFlagNotLike(String value) {
			addCriterion("MARKER_FLAG not like", value, "markerFlag");
			return (Criteria) this;
		}

		public Criteria andMarkerFlagIn(List<String> values) {
			addCriterion("MARKER_FLAG in", values, "markerFlag");
			return (Criteria) this;
		}

		public Criteria andMarkerFlagNotIn(List<String> values) {
			addCriterion("MARKER_FLAG not in", values, "markerFlag");
			return (Criteria) this;
		}

		public Criteria andMarkerFlagBetween(String value1, String value2) {
			addCriterion("MARKER_FLAG between", value1, value2, "markerFlag");
			return (Criteria) this;
		}

		public Criteria andMarkerFlagNotBetween(String value1, String value2) {
			addCriterion("MARKER_FLAG not between", value1, value2, "markerFlag");
			return (Criteria) this;
		}

		public Criteria andInputNameIsNull() {
			addCriterion("INPUT_NAME is null");
			return (Criteria) this;
		}

		public Criteria andInputNameIsNotNull() {
			addCriterion("INPUT_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andInputNameEqualTo(String value) {
			addCriterion("INPUT_NAME =", value, "inputName");
			return (Criteria) this;
		}

		public Criteria andInputNameNotEqualTo(String value) {
			addCriterion("INPUT_NAME <>", value, "inputName");
			return (Criteria) this;
		}

		public Criteria andInputNameGreaterThan(String value) {
			addCriterion("INPUT_NAME >", value, "inputName");
			return (Criteria) this;
		}

		public Criteria andInputNameGreaterThanOrEqualTo(String value) {
			addCriterion("INPUT_NAME >=", value, "inputName");
			return (Criteria) this;
		}

		public Criteria andInputNameLessThan(String value) {
			addCriterion("INPUT_NAME <", value, "inputName");
			return (Criteria) this;
		}

		public Criteria andInputNameLessThanOrEqualTo(String value) {
			addCriterion("INPUT_NAME <=", value, "inputName");
			return (Criteria) this;
		}

		public Criteria andInputNameLike(String value) {
			addCriterion("INPUT_NAME like", value, "inputName");
			return (Criteria) this;
		}

		public Criteria andInputNameNotLike(String value) {
			addCriterion("INPUT_NAME not like", value, "inputName");
			return (Criteria) this;
		}

		public Criteria andInputNameIn(List<String> values) {
			addCriterion("INPUT_NAME in", values, "inputName");
			return (Criteria) this;
		}

		public Criteria andInputNameNotIn(List<String> values) {
			addCriterion("INPUT_NAME not in", values, "inputName");
			return (Criteria) this;
		}

		public Criteria andInputNameBetween(String value1, String value2) {
			addCriterion("INPUT_NAME between", value1, value2, "inputName");
			return (Criteria) this;
		}

		public Criteria andInputNameNotBetween(String value1, String value2) {
			addCriterion("INPUT_NAME not between", value1, value2, "inputName");
			return (Criteria) this;
		}

		public Criteria andInputDateIsNull() {
			addCriterion("INPUT_DATE is null");
			return (Criteria) this;
		}

		public Criteria andInputDateIsNotNull() {
			addCriterion("INPUT_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andInputDateEqualTo(String value) {
			addCriterion("INPUT_DATE =", value, "inputDate");
			return (Criteria) this;
		}

		public Criteria andInputDateNotEqualTo(String value) {
			addCriterion("INPUT_DATE <>", value, "inputDate");
			return (Criteria) this;
		}

		public Criteria andInputDateGreaterThan(String value) {
			addCriterion("INPUT_DATE >", value, "inputDate");
			return (Criteria) this;
		}

		public Criteria andInputDateGreaterThanOrEqualTo(String value) {
			addCriterion("INPUT_DATE >=", value, "inputDate");
			return (Criteria) this;
		}

		public Criteria andInputDateLessThan(String value) {
			addCriterion("INPUT_DATE <", value, "inputDate");
			return (Criteria) this;
		}

		public Criteria andInputDateLessThanOrEqualTo(String value) {
			addCriterion("INPUT_DATE <=", value, "inputDate");
			return (Criteria) this;
		}

		public Criteria andInputDateLike(String value) {
			addCriterion("INPUT_DATE like", value, "inputDate");
			return (Criteria) this;
		}

		public Criteria andInputDateNotLike(String value) {
			addCriterion("INPUT_DATE not like", value, "inputDate");
			return (Criteria) this;
		}

		public Criteria andInputDateIn(List<String> values) {
			addCriterion("INPUT_DATE in", values, "inputDate");
			return (Criteria) this;
		}

		public Criteria andInputDateNotIn(List<String> values) {
			addCriterion("INPUT_DATE not in", values, "inputDate");
			return (Criteria) this;
		}

		public Criteria andInputDateBetween(String value1, String value2) {
			addCriterion("INPUT_DATE between", value1, value2, "inputDate");
			return (Criteria) this;
		}

		public Criteria andInputDateNotBetween(String value1, String value2) {
			addCriterion("INPUT_DATE not between", value1, value2, "inputDate");
			return (Criteria) this;
		}

		public Criteria andUpdateNameIsNull() {
			addCriterion("UPDATE_NAME is null");
			return (Criteria) this;
		}

		public Criteria andUpdateNameIsNotNull() {
			addCriterion("UPDATE_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateNameEqualTo(String value) {
			addCriterion("UPDATE_NAME =", value, "updateName");
			return (Criteria) this;
		}

		public Criteria andUpdateNameNotEqualTo(String value) {
			addCriterion("UPDATE_NAME <>", value, "updateName");
			return (Criteria) this;
		}

		public Criteria andUpdateNameGreaterThan(String value) {
			addCriterion("UPDATE_NAME >", value, "updateName");
			return (Criteria) this;
		}

		public Criteria andUpdateNameGreaterThanOrEqualTo(String value) {
			addCriterion("UPDATE_NAME >=", value, "updateName");
			return (Criteria) this;
		}

		public Criteria andUpdateNameLessThan(String value) {
			addCriterion("UPDATE_NAME <", value, "updateName");
			return (Criteria) this;
		}

		public Criteria andUpdateNameLessThanOrEqualTo(String value) {
			addCriterion("UPDATE_NAME <=", value, "updateName");
			return (Criteria) this;
		}

		public Criteria andUpdateNameLike(String value) {
			addCriterion("UPDATE_NAME like", value, "updateName");
			return (Criteria) this;
		}

		public Criteria andUpdateNameNotLike(String value) {
			addCriterion("UPDATE_NAME not like", value, "updateName");
			return (Criteria) this;
		}

		public Criteria andUpdateNameIn(List<String> values) {
			addCriterion("UPDATE_NAME in", values, "updateName");
			return (Criteria) this;
		}

		public Criteria andUpdateNameNotIn(List<String> values) {
			addCriterion("UPDATE_NAME not in", values, "updateName");
			return (Criteria) this;
		}

		public Criteria andUpdateNameBetween(String value1, String value2) {
			addCriterion("UPDATE_NAME between", value1, value2, "updateName");
			return (Criteria) this;
		}

		public Criteria andUpdateNameNotBetween(String value1, String value2) {
			addCriterion("UPDATE_NAME not between", value1, value2, "updateName");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIsNull() {
			addCriterion("UPDATE_DATE is null");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIsNotNull() {
			addCriterion("UPDATE_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateDateEqualTo(String value) {
			addCriterion("UPDATE_DATE =", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotEqualTo(String value) {
			addCriterion("UPDATE_DATE <>", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateGreaterThan(String value) {
			addCriterion("UPDATE_DATE >", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateGreaterThanOrEqualTo(String value) {
			addCriterion("UPDATE_DATE >=", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateLessThan(String value) {
			addCriterion("UPDATE_DATE <", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateLessThanOrEqualTo(String value) {
			addCriterion("UPDATE_DATE <=", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateLike(String value) {
			addCriterion("UPDATE_DATE like", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotLike(String value) {
			addCriterion("UPDATE_DATE not like", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIn(List<String> values) {
			addCriterion("UPDATE_DATE in", values, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotIn(List<String> values) {
			addCriterion("UPDATE_DATE not in", values, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateBetween(String value1, String value2) {
			addCriterion("UPDATE_DATE between", value1, value2, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotBetween(String value1, String value2) {
			addCriterion("UPDATE_DATE not between", value1, value2, "updateDate");
			return (Criteria) this;
		}

		public Criteria andDelsignIsNull() {
			addCriterion("DELSIGN is null");
			return (Criteria) this;
		}

		public Criteria andDelsignIsNotNull() {
			addCriterion("DELSIGN is not null");
			return (Criteria) this;
		}

		public Criteria andDelsignEqualTo(Integer value) {
			addCriterion("DELSIGN =", value, "delsign");
			return (Criteria) this;
		}

		public Criteria andDelsignNotEqualTo(Integer value) {
			addCriterion("DELSIGN <>", value, "delsign");
			return (Criteria) this;
		}

		public Criteria andDelsignGreaterThan(Integer value) {
			addCriterion("DELSIGN >", value, "delsign");
			return (Criteria) this;
		}

		public Criteria andDelsignGreaterThanOrEqualTo(Integer value) {
			addCriterion("DELSIGN >=", value, "delsign");
			return (Criteria) this;
		}

		public Criteria andDelsignLessThan(Integer value) {
			addCriterion("DELSIGN <", value, "delsign");
			return (Criteria) this;
		}

		public Criteria andDelsignLessThanOrEqualTo(Integer value) {
			addCriterion("DELSIGN <=", value, "delsign");
			return (Criteria) this;
		}

		public Criteria andDelsignIn(List<Integer> values) {
			addCriterion("DELSIGN in", values, "delsign");
			return (Criteria) this;
		}

		public Criteria andDelsignNotIn(List<Integer> values) {
			addCriterion("DELSIGN not in", values, "delsign");
			return (Criteria) this;
		}

		public Criteria andDelsignBetween(Integer value1, Integer value2) {
			addCriterion("DELSIGN between", value1, value2, "delsign");
			return (Criteria) this;
		}

		public Criteria andDelsignNotBetween(Integer value1, Integer value2) {
			addCriterion("DELSIGN not between", value1, value2, "delsign");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table rmbih_user_t
	 * @mbg.generated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rmbih_user_t
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}