package com.rmbih.model;

import java.util.Date;

public class RmbihPicT {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rmbih_pic_t.ID
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rmbih_pic_t.PIC_URL
	 * @mbg.generated
	 */
	private String picUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rmbih_pic_t.PIC_CONTENT
	 * @mbg.generated
	 */
	private String picContent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rmbih_pic_t.PIC_ALT
	 * @mbg.generated
	 */
	private String picAlt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rmbih_pic_t.USER_ID
	 * @mbg.generated
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rmbih_pic_t.INPUT_NAME
	 * @mbg.generated
	 */
	private String inputName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rmbih_pic_t.INPUT_DATE
	 * @mbg.generated
	 */
	private Date inputDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rmbih_pic_t.UPDATE_NAME
	 * @mbg.generated
	 */
	private String updateName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rmbih_pic_t.UPDATE_DATE
	 * @mbg.generated
	 */
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rmbih_pic_t.DELSIGN
	 * @mbg.generated
	 */
	private Integer delsign;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rmbih_pic_t.ID
	 * @return  the value of rmbih_pic_t.ID
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rmbih_pic_t.ID
	 * @param id  the value for rmbih_pic_t.ID
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rmbih_pic_t.PIC_URL
	 * @return  the value of rmbih_pic_t.PIC_URL
	 * @mbg.generated
	 */
	public String getPicUrl() {
		return picUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rmbih_pic_t.PIC_URL
	 * @param picUrl  the value for rmbih_pic_t.PIC_URL
	 * @mbg.generated
	 */
	public void setPicUrl(String picUrl) {
		this.picUrl = picUrl == null ? null : picUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rmbih_pic_t.PIC_CONTENT
	 * @return  the value of rmbih_pic_t.PIC_CONTENT
	 * @mbg.generated
	 */
	public String getPicContent() {
		return picContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rmbih_pic_t.PIC_CONTENT
	 * @param picContent  the value for rmbih_pic_t.PIC_CONTENT
	 * @mbg.generated
	 */
	public void setPicContent(String picContent) {
		this.picContent = picContent == null ? null : picContent.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rmbih_pic_t.PIC_ALT
	 * @return  the value of rmbih_pic_t.PIC_ALT
	 * @mbg.generated
	 */
	public String getPicAlt() {
		return picAlt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rmbih_pic_t.PIC_ALT
	 * @param picAlt  the value for rmbih_pic_t.PIC_ALT
	 * @mbg.generated
	 */
	public void setPicAlt(String picAlt) {
		this.picAlt = picAlt == null ? null : picAlt.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rmbih_pic_t.USER_ID
	 * @return  the value of rmbih_pic_t.USER_ID
	 * @mbg.generated
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rmbih_pic_t.USER_ID
	 * @param userId  the value for rmbih_pic_t.USER_ID
	 * @mbg.generated
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rmbih_pic_t.INPUT_NAME
	 * @return  the value of rmbih_pic_t.INPUT_NAME
	 * @mbg.generated
	 */
	public String getInputName() {
		return inputName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rmbih_pic_t.INPUT_NAME
	 * @param inputName  the value for rmbih_pic_t.INPUT_NAME
	 * @mbg.generated
	 */
	public void setInputName(String inputName) {
		this.inputName = inputName == null ? null : inputName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rmbih_pic_t.INPUT_DATE
	 * @return  the value of rmbih_pic_t.INPUT_DATE
	 * @mbg.generated
	 */
	public Date getInputDate() {
		return inputDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rmbih_pic_t.INPUT_DATE
	 * @param inputDate  the value for rmbih_pic_t.INPUT_DATE
	 * @mbg.generated
	 */
	public void setInputDate(Date inputDate) {
		this.inputDate = inputDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rmbih_pic_t.UPDATE_NAME
	 * @return  the value of rmbih_pic_t.UPDATE_NAME
	 * @mbg.generated
	 */
	public String getUpdateName() {
		return updateName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rmbih_pic_t.UPDATE_NAME
	 * @param updateName  the value for rmbih_pic_t.UPDATE_NAME
	 * @mbg.generated
	 */
	public void setUpdateName(String updateName) {
		this.updateName = updateName == null ? null : updateName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rmbih_pic_t.UPDATE_DATE
	 * @return  the value of rmbih_pic_t.UPDATE_DATE
	 * @mbg.generated
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rmbih_pic_t.UPDATE_DATE
	 * @param updateDate  the value for rmbih_pic_t.UPDATE_DATE
	 * @mbg.generated
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rmbih_pic_t.DELSIGN
	 * @return  the value of rmbih_pic_t.DELSIGN
	 * @mbg.generated
	 */
	public Integer getDelsign() {
		return delsign;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rmbih_pic_t.DELSIGN
	 * @param delsign  the value for rmbih_pic_t.DELSIGN
	 * @mbg.generated
	 */
	public void setDelsign(Integer delsign) {
		this.delsign = delsign;
	}
}