package com.rmbih.model;

public class RmbihUserT {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rmbih_user_t.ID
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rmbih_user_t.LOGIN_NAME
	 * @mbg.generated
	 */
	private String loginName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rmbih_user_t.LOGIN_PASSWORD
	 * @mbg.generated
	 */
	private String loginPassword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rmbih_user_t.USER_NAME
	 * @mbg.generated
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rmbih_user_t.TOKEN
	 * @mbg.generated
	 */
	private String token;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rmbih_user_t.ROLE
	 * @mbg.generated
	 */
	private String role;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rmbih_user_t.STATUS
	 * @mbg.generated
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rmbih_user_t.MARKER_FLAG
	 * @mbg.generated
	 */
	private String markerFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rmbih_user_t.INPUT_NAME
	 * @mbg.generated
	 */
	private String inputName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rmbih_user_t.INPUT_DATE
	 * @mbg.generated
	 */
	private String inputDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rmbih_user_t.UPDATE_NAME
	 * @mbg.generated
	 */
	private String updateName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rmbih_user_t.UPDATE_DATE
	 * @mbg.generated
	 */
	private String updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rmbih_user_t.DELSIGN
	 * @mbg.generated
	 */
	private Integer delsign;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rmbih_user_t.ID
	 * @return  the value of rmbih_user_t.ID
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rmbih_user_t.ID
	 * @param id  the value for rmbih_user_t.ID
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rmbih_user_t.LOGIN_NAME
	 * @return  the value of rmbih_user_t.LOGIN_NAME
	 * @mbg.generated
	 */
	public String getLoginName() {
		return loginName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rmbih_user_t.LOGIN_NAME
	 * @param loginName  the value for rmbih_user_t.LOGIN_NAME
	 * @mbg.generated
	 */
	public void setLoginName(String loginName) {
		this.loginName = loginName == null ? null : loginName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rmbih_user_t.LOGIN_PASSWORD
	 * @return  the value of rmbih_user_t.LOGIN_PASSWORD
	 * @mbg.generated
	 */
	public String getLoginPassword() {
		return loginPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rmbih_user_t.LOGIN_PASSWORD
	 * @param loginPassword  the value for rmbih_user_t.LOGIN_PASSWORD
	 * @mbg.generated
	 */
	public void setLoginPassword(String loginPassword) {
		this.loginPassword = loginPassword == null ? null : loginPassword.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rmbih_user_t.USER_NAME
	 * @return  the value of rmbih_user_t.USER_NAME
	 * @mbg.generated
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rmbih_user_t.USER_NAME
	 * @param userName  the value for rmbih_user_t.USER_NAME
	 * @mbg.generated
	 */
	public void setUserName(String userName) {
		this.userName = userName == null ? null : userName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rmbih_user_t.TOKEN
	 * @return  the value of rmbih_user_t.TOKEN
	 * @mbg.generated
	 */
	public String getToken() {
		return token;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rmbih_user_t.TOKEN
	 * @param token  the value for rmbih_user_t.TOKEN
	 * @mbg.generated
	 */
	public void setToken(String token) {
		this.token = token == null ? null : token.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rmbih_user_t.ROLE
	 * @return  the value of rmbih_user_t.ROLE
	 * @mbg.generated
	 */
	public String getRole() {
		return role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rmbih_user_t.ROLE
	 * @param role  the value for rmbih_user_t.ROLE
	 * @mbg.generated
	 */
	public void setRole(String role) {
		this.role = role == null ? null : role.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rmbih_user_t.STATUS
	 * @return  the value of rmbih_user_t.STATUS
	 * @mbg.generated
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rmbih_user_t.STATUS
	 * @param status  the value for rmbih_user_t.STATUS
	 * @mbg.generated
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rmbih_user_t.MARKER_FLAG
	 * @return  the value of rmbih_user_t.MARKER_FLAG
	 * @mbg.generated
	 */
	public String getMarkerFlag() {
		return markerFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rmbih_user_t.MARKER_FLAG
	 * @param markerFlag  the value for rmbih_user_t.MARKER_FLAG
	 * @mbg.generated
	 */
	public void setMarkerFlag(String markerFlag) {
		this.markerFlag = markerFlag == null ? null : markerFlag.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rmbih_user_t.INPUT_NAME
	 * @return  the value of rmbih_user_t.INPUT_NAME
	 * @mbg.generated
	 */
	public String getInputName() {
		return inputName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rmbih_user_t.INPUT_NAME
	 * @param inputName  the value for rmbih_user_t.INPUT_NAME
	 * @mbg.generated
	 */
	public void setInputName(String inputName) {
		this.inputName = inputName == null ? null : inputName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rmbih_user_t.INPUT_DATE
	 * @return  the value of rmbih_user_t.INPUT_DATE
	 * @mbg.generated
	 */
	public String getInputDate() {
		return inputDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rmbih_user_t.INPUT_DATE
	 * @param inputDate  the value for rmbih_user_t.INPUT_DATE
	 * @mbg.generated
	 */
	public void setInputDate(String inputDate) {
		this.inputDate = inputDate == null ? null : inputDate.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rmbih_user_t.UPDATE_NAME
	 * @return  the value of rmbih_user_t.UPDATE_NAME
	 * @mbg.generated
	 */
	public String getUpdateName() {
		return updateName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rmbih_user_t.UPDATE_NAME
	 * @param updateName  the value for rmbih_user_t.UPDATE_NAME
	 * @mbg.generated
	 */
	public void setUpdateName(String updateName) {
		this.updateName = updateName == null ? null : updateName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rmbih_user_t.UPDATE_DATE
	 * @return  the value of rmbih_user_t.UPDATE_DATE
	 * @mbg.generated
	 */
	public String getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rmbih_user_t.UPDATE_DATE
	 * @param updateDate  the value for rmbih_user_t.UPDATE_DATE
	 * @mbg.generated
	 */
	public void setUpdateDate(String updateDate) {
		this.updateDate = updateDate == null ? null : updateDate.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rmbih_user_t.DELSIGN
	 * @return  the value of rmbih_user_t.DELSIGN
	 * @mbg.generated
	 */
	public Integer getDelsign() {
		return delsign;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rmbih_user_t.DELSIGN
	 * @param delsign  the value for rmbih_user_t.DELSIGN
	 * @mbg.generated
	 */
	public void setDelsign(Integer delsign) {
		this.delsign = delsign;
	}
}