package com.rmbih.dao;

import com.rmbih.model.RmbihUserT;
import com.rmbih.model.RmbihUserTExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RmbihUserTMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rmbih_user_t
	 * @mbg.generated
	 */
	long countByExample(RmbihUserTExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rmbih_user_t
	 * @mbg.generated
	 */
	int deleteByExample(RmbihUserTExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rmbih_user_t
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rmbih_user_t
	 * @mbg.generated
	 */
	int insert(RmbihUserT record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rmbih_user_t
	 * @mbg.generated
	 */
	int insertSelective(RmbihUserT record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rmbih_user_t
	 * @mbg.generated
	 */
	List<RmbihUserT> selectByExample(RmbihUserTExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rmbih_user_t
	 * @mbg.generated
	 */
	RmbihUserT selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rmbih_user_t
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") RmbihUserT record, @Param("example") RmbihUserTExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rmbih_user_t
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") RmbihUserT record, @Param("example") RmbihUserTExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rmbih_user_t
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(RmbihUserT record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rmbih_user_t
	 * @mbg.generated
	 */
	int updateByPrimaryKey(RmbihUserT record);
}